apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: karpenter
  namespace: karpenter
spec:
  generators:
  - list:
      elements:
      - cluster: "release"
        url: "https://kubernetes.default.svc"
  template:
    metadata:
      name: "karpenter"
    spec:
      project: karpenter
      source:
        # ArgoCD will create a pull command by combining {source.repoURL}/{source.chart}
        repoURL: public.ecr.aws/karpenter
        targetRevision: "v0.20.2"
        chart: karpenter
        path: ""
        helm:
          version: v3
          releaseName: karpenter
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - values.yaml
      destination:
        server: '{{ url }}'
        namespace: "karpenter"
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
        - CreateNamespace=false
